[versions]
agp = "8.13.2"
kotlin = "2.0.21"
coreKtx = "1.17.0"
coroutines = "1.9.0"
dadb = "1.2.8"
tensorflowLite = "2.14.0"
junit = "4.13.2"
json = "20250517"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
dadb = { group = "dev.mobile", name = "dadb", version.ref = "dadb" }
tensorflow-lite = { group = "org.tensorflow", name = "tensorflow-lite", version.ref = "tensorflowLite" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
json = { group = "org.json", name = "json", version.ref = "json" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
